version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/natours
      - NGROK_AUTHTOKEN=2iMAMjsxKNJUABhg6y1MAYNCnZY_6hXg5naXLefKKdjJ3afGe
      - NODE_ENV=development
      - PORT=8000
      - DATABASE_PASSWORD=normaniman
      - DATABASE=mongodb+srv://norman:<PASSWORD>@cluster0.2f1wr4p.mongodb.net/natours?retryWrites=true
      - DATABASE_LOCAL=mongodb://127.0.0.1:27017/natours?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.0
      - JWT_SECRET=g;J8HMjHXgWgR?r5Lq0g9v_,zaPfJ7bZ
      - JWT_EXPIRES_IN=90d
      - JWT_COOKIE_EXPIRES_IN=90      - 

      - EMAIL_USERNAME=af8274a29740fa
      - EMAIL_PASSWORD=dac04cdb65b207
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_PORT=2525

      - API_KEY=AIzaSyDB8nyHR4QckxeGKCc3yKY3fSQKy-aK9OE
      - NGROK_AUTHTOKEN=2iMAMjsxKNJUABhg6y1MAYNCnZY_6hXg5naXLefKKdjJ3afGe
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
